name: Create and Push File

run-name: ${{ inputs.APP_NAME }}${{ inputs.guid && ' | ' || '' }}${{ inputs.guid }}
# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      guid:
        description: 'Unique Indentifier [optional] :(Unique String to identify the Workflow e.g. project Provisioning)' 
        type: string
      COST_CENTER:
        description: 'COST_CENTER ID :(COST_CENTER ID)'
        required: true
        type: string   
      BILLING_ACCOUNT_ID:
        description: 'BILLING account ID :(BILLING account ID)'
        required: true
        type: string   

jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3

      - name: Git Config
        run: |
          echo "hello"
          
      - name: Commit and push
        run: |
          git clone https://github.com/prkpushp/ghatest.git
          cd POC_MYKRONOS_GCP_ENV
          git checkout -b testonline1
          echo $? 
          git config --local user.name 'Pushp Ranjan'
          echo $?
          echo "Hello" > my_file.txt
          echo "Hello there" >> my_file.txt
          git add .
          git commit -m "Commit changes"
          git push




